### ISSUE TITLE
Windows computer does not resolve anything

### ISSUE THREAD

**Issue by grm** [steamcache/steamcache-dns#19]
Issue Description:
My computer does not resolve anything while switching to the DNS hosted in the container
Docker Run Command:

I am using docker-compose with this configuration : 
```
version: '2'
services:
  steamcache:
    restart: always
    image: steamcache/steamcache
    ports:
      - "80:80"
    volumes:
      - /opt/data/docker-data/steamcache/data/logs-steam:/data/logs:Z
      - /opt/data/docker-data/steamcache/data/cache-steam:/data/cache:Z
      - /opt/data/docker-data/steamcache/data/www-steam:/var/www:Z

  genericcache:
    restart: always
    image: steamcache/generic
    ports:
      - "81:80"
    volumes:
      - /opt/data/docker-data/steamcache/data/logs-generic:/data/logs:Z
      - /opt/data/docker-data/steamcache/data/cache-generic:/data/cache:Z
      - /opt/data/docker-data/steamcache/data/www-generic:/var/www:Z

  steamcachedns:
    restart: always
    image: steamcache/steamcache-dns
    ports:
      - "53:53/udp"
    volumes:
      - /opt/data/docker-data/gitlab/data/postgresql/data:/var/lib/postgresql:Z
      - /opt/data/docker-data/gitlab/data/postgresql/log:/var/log/postgresql:Z
      - /opt/data/docker-data/gitlab/data/postgresql/run:/run/postgresql:Z
    environment:
      - STEAMCACHE_IP=192.168.43.2
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=192.168.43.2:81
      - DISABLE_WINDOWS=true
    depends_on:
      - steamcache
```

I also tried with the netork adress of docker0 in STEAMCACHE_IP and LANCACHE_IP

Docker Container Output:

```
Starting steamcache_steamcache_1
Starting steamcache_genericcache_1
Recreating steamcache_steamcachedns_1
Attaching to steamcache_steamcache_1, steamcache_genericcache_1, steamcache_steamcachedns_1
steamcache_1     | nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
genericcache_1   | nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
steamcache_1     | nginx: configuration file /etc/nginx/nginx.conf test is successful
genericcache_1   | nginx: configuration file /etc/nginx/nginx.conf test is successful
steamcachedns_1  | Running bootstrap.sh...
steamcachedns_1  | Enabling cache for Blizzard
steamcachedns_1  | Enabling cache for Frontier
steamcachedns_1  | Enabling cache for Origin
steamcachedns_1  | Enabling cache for Riot
steamcachedns_1  | Enabling cache for Steam
steamcachedns_1  | Enabling cache for Uplay
steamcachedns_1  | bootstrap finished.
steamcachedns_1  | checking Bind9 config
steamcachedns_1  | Running Bind9
```

Here is the symptoms from my windows computer 

```
c:\PortQryV2>ping www.google.fr
Ping request could not find host www.google.fr. Please check the name and try again.

c:\PortQryV2>nslookup www.google.fr
Server:  UnKnown
Address:  192.168.43.2

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** UnKnown can't find www.google.fr: Server failed

c:\PortQryV2>PortQry.exe -n 192.168.43.2 -e 53 -p UDP

Querying target system called:

 192.168.43.2

querying...

UDP port 53 (domain service): LISTENING

```

Any help would be greatly appreciated,
Thx !
