### ISSUE TITLE
unable to assign static IP with docker-compose

### ISSUE THREAD

**Issue by matthewh86** [steamcache/steamcache-dns#35]
**Issue Description:**
I'm trying to get these images working using docker-compose instead of individual docker commands, but I can't seem to get them working with static IPs. When I run `docker inspect DNS_CONTAINER_ID | grep "IPAddress"` I get:
```
"SecondaryIPAddresses": null,
"IPAddress": "",
        "IPAddress": "192.168.1.253",
```
but I can't ping or curl that IP.

**Docker Run Command:**
```
version: '3.4'

services:

  gamecache-dns:
    image: steamcache/steamcache-dns:latest
    container_name: gamecache-dns
    ports:
      - "53:53/udp"
    environment:
      - USE_GENERIC_CACHE=false
      # - LANCACHE_IP=genericcache
      - STEAMCACHE_IP=steamcache
      # - ORIGINCACHE_IP=origincache
      # - BLIZZARDCACHE_IP=blizzardcache
      # - UPLAYCACHE_IP=uplaycache
      # - FRONTIERCACHE_IP=frontiercache
      # - RIOTCACHE_IP=riotcache
      # - WINDOWSCACHE_IP=windowscache
      - DISABLE_STEAM=false
      - DISABLE_ORIGIN=true
      - DISABLE_BLIZZARD=true
      - DISABLE_UPLAY=true
      - DISABLE_FRONTIER=true
      - DISABLE_RIOT=true
      - DISABLE_WINDOWS=true
      - UPSTREAM_DNS=8.8.8.8
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.253
    restart: unless-stopped
    volumes:
      - gamecache-dns-volume:/data
      - gamecache-dns-volume:/tmp
      - gamecache-dns-volume:/var/logs

  steamcache:
    image: steamcache/steamcache:latest
    container_name: steamcache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      - gamecache_vlan
    restart: unless-stopped
    volumes:
      - steamcache-volume:/data
      - steamcache-volume:/tmp

networks:
  gamecache_vlan:
    driver: macvlan
#    driver_opts:
#      parent: enp1s0f0.30
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  gamecache-dns-volume:
    driver_opts:
      type: none 
      device: /srv/docker/gamecache/dns
      o: bind
  steamcache-volume:
    driver_opts:
      type: none 
      device: /srv/docker/gamecache/steam
      o: bind
```

**Comment by JasonRivers** [comment]
The issue you have here is that you have set the environment variable "STEAMCACHE_IP=steamcache - Currently the  DNS image doesn't know how to deal with a named service, it expects an IP address in there.

The best thing to do for the moment is to set ```STEAMCACHE_IP=192.168.1.50``` and then set ipv4_address on the steamcache container.

E.G:

```yml
version: '3.4'

services:

  gamecache-dns:
    image: steamcache/steamcache-dns:latest
    container_name: gamecache-dns
    ports:
      - "53:53/udp"
    environment:
      - USE_GENERIC_CACHE=false
      # - LANCACHE_IP=genericcache
      - STEAMCACHE_IP=192.168.1.50
      # - ORIGINCACHE_IP=origincache
      # - BLIZZARDCACHE_IP=blizzardcache
      # - UPLAYCACHE_IP=uplaycache
      # - FRONTIERCACHE_IP=frontiercache
      # - RIOTCACHE_IP=riotcache
      # - WINDOWSCACHE_IP=windowscache
      - DISABLE_STEAM=false
      - DISABLE_ORIGIN=true
      - DISABLE_BLIZZARD=true
      - DISABLE_UPLAY=true
      - DISABLE_FRONTIER=true
      - DISABLE_RIOT=true
      - DISABLE_WINDOWS=true
      - UPSTREAM_DNS=8.8.8.8
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.253
    restart: unless-stopped
    volumes:
      - gamecache-dns-volume:/data
      - gamecache-dns-volume:/tmp
      - gamecache-dns-volume:/var/logs

  steamcache:
    image: steamcache/steamcache:latest
    container_name: steamcache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.50
    restart: unless-stopped
    volumes:
      - steamcache-volume:/data
      - steamcache-volume:/tmp

networks:
  gamecache_vlan:
    driver: macvlan
#    driver_opts:
#      parent: enp1s0f0.30
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  gamecache-dns-volume:
    driver_opts:
      type: none
      device: /srv/docker/gamecache/dns
      o: bind
  steamcache-volume:
    driver_opts:
      type: none
      device: /srv/docker/gamecache/steam
      o: bind

```

Hope this helps.
